<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro" name="reppy_bot">
	
<xacro:include filename="$(find reppy_bot_urdf)/urdf/consts.xacro"/>
<xacro:include filename="$(find reppy_bot_urdf)/urdf/diff_drive_setup.xacro"/>
<xacro:include filename="$(find reppy_bot_urdf)/urdf/sensors.xacro"/> 
	
	 
<!-- Simple Robot Settings -->
<xacro:property name="chassis_height" value="0.15"/>
<xacro:property name="chassis_width"  value="${chassis_height*1.618}"/>  
<xacro:property name="chassis_len"    value="${chassis_width+chassis_height}"/>
<xacro:property name="chassis_floor_clearance" value="${chassis_height/(1.618*2)}"/>

<xacro:property name="wheel_diameter" value="${chassis_len/(1.618*1.618)}"/>  
<xacro:property name="wheel_width" value="${chassis_width/(16.18)}"/>  
<xacro:property name="wheel_base_center_x" value="${chassis_len/(-1.618*3)}"/>  
<xacro:property name="caster_collision_x" value="${chassis_len/(1.618*2)}"/>


<link name="base_link"/>
<link name="chassis">
	
	<visual>
		<geometry>
			<box size="${chassis_len} ${chassis_width} ${chassis_height}" />
		</geometry>
		<material name="Green">
			<color rgba="0 1 0 0.5"/>
		</material>
	</visual>
	<collision>
		<geometry>
			<box size="${chassis_len} ${chassis_width} ${chassis_height}" />
		</geometry>
	</collision>
	<inertial>
            <mass value="1.0"/>
            <origin xyz="0.0 0.0 0.0"/>
            <inertia ixx="0.1" 
                     iyy="0.1" 
                     izz="0.1"
  	            	 iyz="0.0"
		             ixy="0.0" 
		             ixz="0.0"/>
    </inertial>
</link>

<gazebo reference="chassis">
	<material value="Gazebo/Green"/>
</gazebo>

<joint name="base_chassis_joint" type="fixed">
	<parent link="base_link" />
	<child link="chassis" />
	<origin xyz="0 0 ${chassis_floor_clearance+chassis_height/2}" rpy="0 0 0" />
</joint>



<link name="caster_collision">
	<visual>
		<geometry>
			<sphere radius="${chassis_floor_clearance}" />
		</geometry>
		<material name="Black">
			<color rgba="0 0 0 1"/>
		</material>
	</visual>
	<collision>
		<geometry>
			<sphere radius="${chassis_floor_clearance}" />
		</geometry>
	</collision>

    <inertial>
    <mass value="1.0"/>
    <origin xyz="0.0 0.0 0.0"/>
    <inertia ixx="0.1" 
             iyy="0.1" 
             izz="0.1"
        	 iyz="0.0"
             ixy="0.0" 
             ixz="0.0"/>
    </inertial>
</link>
<gazebo reference="caster_collision">
	<material value="Gazebo/FlatBlack"/>
</gazebo>
<joint name="base_caster_col_joint" type="fixed">
	<parent link="base_link" />
	<child link="caster_collision" />
	<origin xyz="${caster_collision_x} 0 ${chassis_floor_clearance}" rpy="0 0 0" />
</joint>

<xacro:diff_drive_setup 
	 base_frame="base_link"
	 robot_namespace=""
	 wheel_base_center_x="${wheel_base_center_x}"
     wheel_separation ="${chassis_width}"
     wheel_diameter="${wheel_diameter}"
	 wheel_width="${wheel_width}"
     wheel_torque="5"
	 wheel_acceleration="1"
	 wheel_joint_limit_vel="2"
	 wheel_joint_limit_effort="2"
	 wheel_friction1="100000"
     wheel_friction2="1000"
	 wheel_contact_damping="100.0"
     wheel_contact_stiffness="1000000.0"
	 wheel_mass="3"
     cmd_topic="/cmd_vel"
	 odom_topic="odom"
     odom_frame="odom"
	 ros_plugin_always_on="true"
	 ros_plugin_controller_name="diff_drv0"
     ros_plugin_update_rate="100"
	 ros_plugin_odom_source="encoder"
	 ros_plugin_publish_wheel_joint_state="true"
	 ros_plugin_publish_wheel_tf="true"
	 ros_plugin_publish_tf="1" />      	
	


<xacro:gps_receiver  id="0"
					 parent_link="chassis"
					 x="0" y="0" z="0"
					 frame_id="world"
					 topic_name="/fix"
					 velocity_topic_name="/fix_vel"
					 reference_latitude="49"
					 reference_longitude="8"
					 reference_heading="0"
					 reference_altitude="0"/>

<xacro:imu 	id="0"
			topic_name="/imu"
			parent_link="chassis"
			x="${wheel_base_center_x}"
			y="0"
			z="0"
			roll="0"
			pitch="0"
			yaw="0"
			gaussian_noise="2.89e-08"
			/>

</robot>
											